/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Complete_Indiv_game extends javax.swing.JFrame {

    private static final String URL = "jdbc:oracle:thin:@localhost:1521:xe"; // Update with your database URL
    private static final String USERNAME = "system"; // Update with your database username
    private static final String PASSWORD = "cristianosui7";
    public Complete_Indiv_game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        game_sel = new javax.swing.JComboBox<>();
        check_pl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_pl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        game_id_field = new javax.swing.JTextField();
        pl_first = new javax.swing.JTextField();
        pl_sec = new javax.swing.JTextField();
        pl_thi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        con_res = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(236, 131, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select the Game");

        game_sel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        game_sel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Running", "Tennis", "Badminton", "Boxing", "Shooting", "Swimming" }));

        check_pl.setBackground(new java.awt.Color(2, 76, 170));
        check_pl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        check_pl.setForeground(new java.awt.Color(255, 255, 255));
        check_pl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-search-32.png"))); // NOI18N
        check_pl.setText("Search");
        check_pl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_plActionPerformed(evt);
            }
        });

        show_pl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        show_pl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Particpant ID", "Participant Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(show_pl);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select the Game_ID");

        game_id_field.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pl_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pl_secActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("First");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Second");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Third");

        con_res.setBackground(new java.awt.Color(2, 76, 170));
        con_res.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        con_res.setForeground(new java.awt.Color(255, 255, 255));
        con_res.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-confirm-50 (1).png"))); // NOI18N
        con_res.setText("Confirm");
        con_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_resActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-test-results-48.png"))); // NOI18N
        jLabel1.setText("Provide Results");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pl_first, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(pl_sec, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pl_thi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(game_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(game_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(check_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(con_res, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(game_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(game_id_field))
                .addGap(18, 18, 18)
                .addComponent(check_pl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pl_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pl_sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pl_thi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(con_res, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pl_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pl_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pl_secActionPerformed

    private void check_plActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_plActionPerformed
        // TODO add your handling code here:
        String selectedGame = (String) game_sel.getSelectedItem();
        String sel_game_id = game_id_field.getText();
        DefaultTableModel model = (DefaultTableModel) show_pl.getModel(); 
    model.setRowCount(0); 
        
        if (selectedGame != null && !selectedGame.isEmpty()) {
        try (Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
             PreparedStatement ps = conn.prepareStatement("SELECT PARTICIPANT_ID,USERNAME FROM GAME_PARTICIPANTS WHERE GAME_ID = ?")){
            ps.setString(1, sel_game_id);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                String par_id = rs.getString("PARTICIPANT_ID");
                String user_id = rs.getString("USERNAME");
                model.addRow(new Object[]{par_id,user_id});
            }
            rs.close();
            ps.close();
            conn.close();
            
        }   catch (SQLException ex) {
                Logger.getLogger(Complete_Indiv_game.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select the required fields.");
        }
        
    }//GEN-LAST:event_check_plActionPerformed

    private void con_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_resActionPerformed
      String p_first = pl_first.getText();   // First place participant
    String p_second = pl_sec.getText();    // Second place participant
    String p_third = pl_thi.getText();     // Third place participant
    String gameId = game_id_field.getText();  // Game ID
    String sportType = (String) game_sel.getSelectedItem();  // Sport Type

    // Points for first, second, third places
    int pointsFirst = 10;
    int pointsSecond = 5;
    int pointsThird = 3;

    // Validate input fields
    if (p_first != null && !p_first.isEmpty() && 
        p_second != null && !p_second.isEmpty() && 
        p_third != null && !p_third.isEmpty() && 
        gameId != null && !gameId.isEmpty()) {

        // Insert results into the database and store points
        try (Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
            
            // Insert results into individual_game_results table
            String insertGameResultsSQL = "INSERT INTO individual_game_results (GAME_ID, SPORT_TYPE, FIRST, SECOND, THIRD) VALUES (?, ?, ?, ?, ?)";
            try (PreparedStatement psGameResults = conn.prepareStatement(insertGameResultsSQL)) {
                psGameResults.setString(1, gameId);  // Game ID
                psGameResults.setString(2, sportType);  // Sport Type
                psGameResults.setString(3, p_first); // First place participant
                psGameResults.setString(4, p_second); // Second place participant
                psGameResults.setString(5, p_third); // Third place participant
                
                int rowsAffected = psGameResults.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Results have been successfully saved.");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to save results.");
                }
            }

            // Upsert points for first, second, and third place participants including sport_type
            String upsertPointsSQL = "MERGE INTO player_points pp " +
                                      "USING (SELECT ? AS player_name, ? AS game_id, ? AS points, ? AS sport_type FROM dual) incoming " +
                                      "ON (pp.PLAYER_NAME = incoming.player_name AND pp.GAME_ID = incoming.game_id AND pp.SPORT_TYPE = incoming.sport_type) " +
                                      "WHEN MATCHED THEN " +
                                      "UPDATE SET pp.POINTS = pp.POINTS + incoming.points " +
                                      "WHEN NOT MATCHED THEN " +
                                      "INSERT (pp.PLAYER_NAME, pp.GAME_ID, pp.POINTS, pp.SPORT_TYPE) " +
                                      "VALUES (incoming.player_name, incoming.game_id, incoming.points, incoming.sport_type)";

            try (PreparedStatement psPlayerPoints = conn.prepareStatement(upsertPointsSQL)) {
                // Upsert points for 1st place
                psPlayerPoints.setString(1, p_first);  // Player Name
                psPlayerPoints.setString(2, gameId);   // Game ID
                psPlayerPoints.setInt(3, pointsFirst); // Points (10 for 1st)
                psPlayerPoints.setString(4, sportType); // Sport Type
                psPlayerPoints.executeUpdate();
                
                // Upsert points for 2nd place
                psPlayerPoints.setString(1, p_second); // Player Name
                psPlayerPoints.setString(2, gameId);   // Game ID
                psPlayerPoints.setInt(3, pointsSecond); // Points (5 for 2nd)
                psPlayerPoints.setString(4, sportType); // Sport Type
                psPlayerPoints.executeUpdate();
                
                // Upsert points for 3rd place
                psPlayerPoints.setString(1, p_third);  // Player Name
                psPlayerPoints.setString(2, gameId);   // Game ID
                psPlayerPoints.setInt(3, pointsThird); // Points (3 for 3rd)
                psPlayerPoints.setString(4, sportType); // Sport Type
                psPlayerPoints.executeUpdate();
            }

        } catch (SQLException ex) {
            Logger.getLogger(Complete_Indiv_game.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        // Show error message if fields are not filled
        JOptionPane.showMessageDialog(this, "Please fill in all the fields (First, Second, Third, Game ID).");
    }
    }//GEN-LAST:event_con_resActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Create_Game().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complete_Indiv_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complete_Indiv_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complete_Indiv_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complete_Indiv_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Complete_Indiv_game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_pl;
    private javax.swing.JButton con_res;
    private javax.swing.JTextField game_id_field;
    private javax.swing.JComboBox<String> game_sel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pl_first;
    private javax.swing.JTextField pl_sec;
    private javax.swing.JTextField pl_thi;
    private javax.swing.JTable show_pl;
    // End of variables declaration//GEN-END:variables
}
