/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class Complete_Team_game extends javax.swing.JFrame {

    private static final String URL = "jdbc:oracle:thin:@localhost:1521:xe"; // Update with your database URL
    private static final String USERNAME = "system"; // Update with your database username
    private static final String PASSWORD = "cristianosui7";
    public Complete_Team_game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        game_sel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        game_id_field = new javax.swing.JTextField();
        check_btn = new javax.swing.JButton();
        t1 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JRadioButton();
        res_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(236, 131, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select the Game");

        game_sel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        game_sel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Football", "Cricket", "Basketball", "Hockey", "Volleyball" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter the Game_ID");

        game_id_field.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        check_btn.setBackground(new java.awt.Color(2, 76, 170));
        check_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        check_btn.setForeground(new java.awt.Color(255, 255, 255));
        check_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-search-32.png"))); // NOI18N
        check_btn.setText("Find");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });

        t1.setBackground(new java.awt.Color(255, 0, 0));
        t1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t1.setText("Team1");

        t2.setBackground(new java.awt.Color(255, 0, 0));
        t2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t2.setText("Team2");

        res_btn.setBackground(new java.awt.Color(2, 76, 170));
        res_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        res_btn.setForeground(new java.awt.Color(255, 255, 255));
        res_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-confirm-50 (1).png"))); // NOI18N
        res_btn.setText("Confirm");
        res_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-test-results-48.png"))); // NOI18N
        jLabel1.setText("Provide Results");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(game_sel, 0, 167, Short.MAX_VALUE)
                    .addComponent(game_id_field)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(res_btn)
                    .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(game_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(game_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2)
                    .addComponent(t1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(res_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        // TODO add your handling code here:
        String selectedGame = (String) game_sel.getSelectedItem();
        String sel_game_id = game_id_field.getText();

    if (selectedGame != null && !selectedGame.isEmpty()) {
        try (Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
             PreparedStatement ps = conn.prepareStatement("SELECT TEAM1_ID, TEAM2_ID FROM games_team WHERE GAME_NAME = ? AND GAME_ID = ?")) {
            ps.setString(1, selectedGame);
            ps.setString(2,sel_game_id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String team1 = rs.getString("TEAM1_ID");
                String team2 = rs.getString("TEAM2_ID");
                
                // Set the team names in the radio buttons
                t1.setText(team1);
                t2.setText(team2);
                
                t1.setVisible(true);
                t2.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No teams found for the selected game.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching teams: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a game to view teams.");
    }
    }//GEN-LAST:event_check_btnActionPerformed

    private void res_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_btnActionPerformed
        String selectedGame = (String) game_sel.getSelectedItem();
    String sel_game_id = game_id_field.getText();
    String team1 = t1.getText();
    String team2 = t2.getText();
    String winner = t1.isSelected() ? team1 : t2.isSelected() ? team2 : "";
    String loser = winner.equals(team1) ? team2 : team1;

    if (!winner.isEmpty()) {
        try (Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {

            // Insert game results
            try (PreparedStatement ps = conn.prepareStatement("INSERT INTO game_results (GAME_ID, TEAM1, TEAM2, WINNER, LOSER) VALUES (?, ?, ?, ?, ?)")) {
                ps.setString(1, sel_game_id);
                ps.setString(2, team1);
                ps.setString(3, team2);
                ps.setString(4, winner);
                ps.setString(5, loser);
                ps.executeUpdate();
            }

            // Update points for the winning team
            updateTeamPoints(conn, winner, 5);  // Add 5 points to winner
            updateTeamPoints(conn, loser, 0);   // No points for loser

            JOptionPane.showMessageDialog(this, "Results confirmed! Winner: " + winner);
            new Finish_Game().setVisible(true);
            this.dispose();

            // Clear selection
            t1.setSelected(false);
            t2.setSelected(false);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error storing result: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a winner.");
    }
    }//GEN-LAST:event_res_btnActionPerformed

    
    private void updateTeamPoints(Connection conn, String teamId, int pointsToAdd) throws SQLException {
    try (PreparedStatement psCheck = conn.prepareStatement("SELECT POINTS FROM team_points WHERE TEAM_ID = ?")) {
        psCheck.setString(1, teamId);
        ResultSet rs = psCheck.executeQuery();

        if (rs.next()) {
            // Team exists, update points
            int currentPoints = rs.getInt("POINTS");
            int newPoints = currentPoints + pointsToAdd;
            try (PreparedStatement psUpdate = conn.prepareStatement("UPDATE team_points SET POINTS = ? WHERE TEAM_ID = ?")) {
                psUpdate.setInt(1, newPoints);
                psUpdate.setString(2, teamId);
                psUpdate.executeUpdate();
            }
        } else {
            // Team does not exist, insert new record
            try (PreparedStatement psInsert = conn.prepareStatement("INSERT INTO team_points (TEAM_ID, POINTS) VALUES (?, ?)")) {
                psInsert.setString(1, teamId);
                psInsert.setInt(2, pointsToAdd);
                psInsert.executeUpdate();
            }
        }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complete_Team_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complete_Team_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complete_Team_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complete_Team_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Complete_Team_game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_btn;
    private javax.swing.JTextField game_id_field;
    private javax.swing.JComboBox<String> game_sel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton res_btn;
    private javax.swing.JRadioButton t1;
    private javax.swing.JRadioButton t2;
    // End of variables declaration//GEN-END:variables
}
