/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgms;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author VICTUS
 */
public class Main_Page_2 extends javax.swing.JFrame {

    /**
     * Creates new form Main_Page
     */
    public Main_Page_2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acc_user_det = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        team_l = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        contact_l = new javax.swing.JLabel();
        player_v = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        te_sche = new javax.swing.JLabel();
        te_reg = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        te_check = new javax.swing.JLabel();
        te_lead = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(236, 131, 5));

        jPanel4.setBackground(new java.awt.Color(9, 16, 87));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SGMS: Your Gateway to Sports Excellence");

        acc_user_det.setBackground(new java.awt.Color(204, 255, 102));
        acc_user_det.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acc_user_det.setForeground(new java.awt.Color(255, 255, 255));
        acc_user_det.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_user_det.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-user-50.png"))); // NOI18N
        acc_user_det.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acc_user_detMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acc_user_detMouseExited(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-logout-30.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acc_user_det, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acc_user_det, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(2, 76, 170));

        team_l.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        team_l.setForeground(new java.awt.Color(102, 255, 102));
        team_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        team_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-team-50.png"))); // NOI18N
        team_l.setText("Teams");
        team_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                team_lMouseClicked(evt);
            }
        });

        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(102, 255, 102));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-home-30.png"))); // NOI18N
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        contact_l.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contact_l.setForeground(new java.awt.Color(102, 255, 102));
        contact_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-contact-30.png"))); // NOI18N
        contact_l.setText("Contact Us");
        contact_l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contact_lMouseClicked(evt);
            }
        });

        player_v.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player_v.setForeground(new java.awt.Color(102, 255, 102));
        player_v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player_v.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-soccer-50.png"))); // NOI18N
        player_v.setText("Player");
        player_v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player_vMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact_l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player_v, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(team_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(team_l, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player_v, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contact_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(236, 131, 5));

        te_sche.setBackground(new java.awt.Color(51, 51, 255));
        te_sche.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        te_sche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te_sche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-schedule-30.png"))); // NOI18N
        te_sche.setText("View Schedule");
        te_sche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te_scheMouseClicked(evt);
            }
        });

        te_reg.setBackground(new java.awt.Color(51, 51, 255));
        te_reg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        te_reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-add-user-male-50.png"))); // NOI18N
        te_reg.setText("Register for a Game");
        te_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te_regMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TEAM");

        te_check.setBackground(new java.awt.Color(236, 131, 5));
        te_check.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        te_check.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-test-results-48.png"))); // NOI18N
        te_check.setText("Check Results");
        te_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te_checkMouseClicked(evt);
            }
        });

        te_lead.setBackground(new java.awt.Color(51, 51, 255));
        te_lead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        te_lead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te_lead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-leaderboard-30.png"))); // NOI18N
        te_lead.setText("LeaderBoard");
        te_lead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te_leadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(te_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(te_sche, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(te_lead, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(te_check, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(te_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(te_sche, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(te_check, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(te_lead, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents




    
    private void acc_user_detMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_user_detMouseEntered
        // TODO add your handling code here:
        UserSession session = UserSession.getInstance();
    String role = session.getRole();
    
    // Assuming the username is part of the session as well
    String username = session.getUsername(); // Replace this with the actual method to get the username, if available

    // Display the username and role on the account label when the mouse hovers over it
    acc_user_det.setText("" + username + " " + role);
    }//GEN-LAST:event_acc_user_detMouseEntered

    private void acc_user_detMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_user_detMouseExited
        // TODO add your handling code here:
        acc_user_det.setText("ACCOUNT");
    }//GEN-LAST:event_acc_user_detMouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        new Login_Page().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        new Main_Page_2().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void team_lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_team_lMouseClicked
        // TODO add your handling code here:
        new Teams_Vw().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_team_lMouseClicked

    private void player_vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player_vMouseClicked
        // TODO add your handling code here:
        new Player_View().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_player_vMouseClicked

    private void contact_lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contact_lMouseClicked
        // TODO add your handling code here:
        new Contact().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_contact_lMouseClicked

    private void te_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te_regMouseClicked
        // TODO add your handling code here:
         if (!te_reg.isEnabled()) {
        return;  // Exit early if the label is disabled
    }
        new Register_Team_Game().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_te_regMouseClicked

    private void te_scheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te_scheMouseClicked
        // TODO add your handling code here:
         if (!te_sche.isEnabled()) {
        return;  // Exit early if the label is disabled
    }
        new View_Team_Schedule().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_te_scheMouseClicked

    private void te_leadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te_leadMouseClicked
        // TODO add your handling code here:
        new View_Team_Board().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_te_leadMouseClicked

    private void te_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te_checkMouseClicked
        // TODO add your handling code here:
        new Team_Results().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_te_checkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Page_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_user_det;
    private javax.swing.JLabel contact_l;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel player_v;
    private javax.swing.JLabel te_check;
    private javax.swing.JLabel te_lead;
    private javax.swing.JLabel te_reg;
    private javax.swing.JLabel te_sche;
    private javax.swing.JLabel team_l;
    // End of variables declaration//GEN-END:variables
}
