/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgms;


import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
public class Register_Team_Game extends javax.swing.JFrame {

    /**
     * Creates new form Register_Team_Game
     */
    public Register_Team_Game() {
        initComponents();
        loadTeamSpecificGames(); 
    
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gameComboBox = new javax.swing.JComboBox<>();
        registerButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        registerButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(236, 131, 5));

        gameComboBox.setBackground(new java.awt.Color(0, 0, 0));
        gameComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gameComboBox.setForeground(new java.awt.Color(255, 255, 255));

        registerButton.setBackground(new java.awt.Color(51, 255, 51));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-confirm-50 (1).png"))); // NOI18N
        registerButton.setText("CONFIRM");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select the game");

        registerButton1.setBackground(new java.awt.Color(255, 51, 51));
        registerButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\VICTUS\\OneDrive\\Documentos\\NetBeansProjects\\DBMS_project\\src\\Images\\close Jframe.png")); // NOI18N
        registerButton1.setText("BACK");
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-team-50.png"))); // NOI18N
        jLabel1.setText("Register for Match");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(gameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void loadTeamSpecificGames() {
     String loggedInUsername = UserSession.getInstance().getUsername();

        if (loggedInUsername == null || loggedInUsername.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No username found. Please log in.");
            return;
        }

        // Fetch the sports type for the logged-in user (team)
        String sportsType = getTeamSportsType(loggedInUsername);

        // Populate games only for the matching sports type
        if (sportsType != null) {
            populateGames(sportsType);
        } else {
            JOptionPane.showMessageDialog(this, "No sports type found for the team.");
        }
    }
     
     private String getTeamSportsType(String username) {
        String sportsType = null;
        try {
            // Database connection details
            String DB_URL = "jdbc:oracle:thin:@localhost:1521:xe";
            String DB_USER = "system";
            String DB_PASS = "cristianosui7";

            Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
            String query = "SELECT SPORTS_TYPE FROM teams_SGMS WHERE USERNAME = ?";

            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, username);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                sportsType = rs.getString("SPORTS_TYPE");
            }

            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return sportsType;
    }
     
    private void populateGames(String sportsType) {
    try {
        // Database connection details
        String DB_URL = "jdbc:oracle:thin:@localhost:1521:xe";
        String DB_USER = "system";
        String DB_PASS = "cristianosui7";

        Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);

        // Query to fetch games for the selected sports type where either TEAM1_ID or TEAM2_ID is still NULL
        String query = "SELECT GAME_ID, GAME_NAME, VENUE, TO_CHAR(GAME_DATE, 'YYYY-MM-DD') AS GAME_DATE " +
                       "FROM games_team " +
                       "WHERE GAME_NAME = ? " +  // Match the sports type
                       "AND (TEAM1_ID IS NULL OR TEAM2_ID IS NULL)"; // Exclude games with two registered teams

        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, sportsType);
        ResultSet rs = pstmt.executeQuery();

        // Clear the combo box before adding new items
        gameComboBox.removeAllItems();

        // Add available games to the combo box with venue and date details
        while (rs.next()) {
            String gameId = rs.getString("GAME_ID");
            String gameName = rs.getString("GAME_NAME");
            String venue = rs.getString("VENUE");
            String gameDate = rs.getString("GAME_DATE"); // formatted as 'YYYY-MM-DD'
            
            // Format the combo box item to include game ID, name, venue, and date
            String gameDetails = gameId + " - " + gameName + " | " + venue + " | " + gameDate;
            gameComboBox.addItem(gameDetails); // Add game details to the combo box
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

     /**
 * Method to register the team for the selected game
 */
/**
 * Method to register the team for the selected game and update the TEAM1_ID or TEAM2_ID in the table.
 */
private void registerTeamForGame(String selectedGameId, String teamUsername) {
    try {
        // Database connection details
        String DB_URL = "jdbc:oracle:thin:@localhost:1521:xe";
        String DB_USER = "system";
        String DB_PASS = "cristianosui7";

        Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);

        // First, check if TEAM1_ID or TEAM2_ID is already the current team
        String query = "SELECT TEAM1_ID, TEAM2_ID FROM games_team WHERE GAME_ID = ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, selectedGameId);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            String team1 = rs.getString("TEAM1_ID");
            String team2 = rs.getString("TEAM2_ID");

            // Check if the team is already registered as TEAM1_ID or TEAM2_ID
            if (teamUsername.equals(team1) || teamUsername.equals(team2)) {
                JOptionPane.showMessageDialog(this, "You are already registered for this game.");
                return; // Exit the method, since the team is already registered
            }

            // Prepare the update query
            String updateQuery = null;

            // If TEAM1_ID is NULL, assign the current team to TEAM1_ID
            if (team1 == null || team1.isEmpty()) {
                updateQuery = "UPDATE games_team SET TEAM1_ID = ? WHERE GAME_ID = ?";
            }
            // If TEAM1_ID is filled and TEAM2_ID is NULL, assign the current team to TEAM2_ID
            else if (team2 == null || team2.isEmpty()) {
                updateQuery = "UPDATE games_team SET TEAM2_ID = ? WHERE GAME_ID = ?";
            } else {
                // Both teams are already registered, no more slots available
                JOptionPane.showMessageDialog(this, "Sorry, this game is already full.");
                return;
            }

            // If update query is prepared, execute it
            if (updateQuery != null) {
                PreparedStatement updateStmt = conn.prepareStatement(updateQuery);
                updateStmt.setString(1, teamUsername); // Set the team username
                updateStmt.setString(2, selectedGameId); // Set the game ID

                int rowsUpdated = updateStmt.executeUpdate(); // Execute the update
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Team registered successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to register the team.");
                }

                // Commit the transaction if auto-commit is disabled
                conn.commit();

                updateStmt.close();
            }
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}


    
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        String selectedGame = (String) gameComboBox.getSelectedItem();
    
    if (selectedGame != null && !selectedGame.isEmpty()) {
        // Extract the GAME_ID from the selected combo box item
        String selectedGameId = selectedGame.split(" - ")[0]; // Assuming the format "GAME_ID - GAME_NAME"
        
        // Get the logged-in team's username
        String teamUsername = UserSession.getInstance().getUsername();

        // Register the team for the selected game
        registerTeamForGame(selectedGameId, teamUsername);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a game to register.");
    }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        // TODO add your handling code here:
        new Main_Page_2().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_registerButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Team_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Team_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Team_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Team_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Team_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> gameComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerButton1;
    // End of variables declaration//GEN-END:variables
}
