/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sgms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;




public class Register_Indiv_Game extends javax.swing.JFrame {

    private static final String URL = "jdbc:oracle:thin:@localhost:1521:xe"; // Update with your database URL
    private static final String USERNAME = "system"; // Update with your database username
    private static final String PASSWORD = "cristianosui7"; // Update with your database password
    public Register_Indiv_Game() {
        initComponents();
        loadSports();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sports_combo = new javax.swing.JComboBox<>();
        con_btn = new javax.swing.JButton();
        con_btn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(236, 131, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select the Game");

        sports_combo.setBackground(new java.awt.Color(0, 0, 0));
        sports_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sports_combo.setForeground(new java.awt.Color(255, 255, 255));

        con_btn.setBackground(new java.awt.Color(51, 255, 51));
        con_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        con_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-confirm-50 (1).png"))); // NOI18N
        con_btn.setText("CONFIRM");
        con_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_btnActionPerformed(evt);
            }
        });

        con_btn1.setBackground(new java.awt.Color(255, 51, 51));
        con_btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        con_btn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\VICTUS\\OneDrive\\Documentos\\NetBeansProjects\\DBMS_project\\src\\Images\\close Jframe.png")); // NOI18N
        con_btn1.setText("BACK");
        con_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_btn1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgms/icons/icons8-add-user-male-50.png"))); // NOI18N
        jLabel1.setText("Register for Individual Game");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(sports_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(con_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(con_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sports_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(con_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void loadSports() {
    String username = UserSession.getInstance().getUsername();
    String sportType = ""; // To hold the sport type of the user

    // Retrieve the sport type for the logged-in user
    try (Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
         PreparedStatement ps = conn.prepareStatement("SELECT SPORT_TYPE FROM players WHERE USERNAME = ?")) {
        ps.setString(1, username);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            sportType = rs.getString("SPORT_TYPE");
            System.out.println("Retrieved sport type: " + sportType);  // Debugging line
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    // Load games based on the player's sport type
    try (Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
         PreparedStatement ps = conn.prepareStatement(
             "SELECT GAME_ID, GAME_NAME, VENUE, TO_CHAR(GAME_DATE, 'YYYY-MM-DD') AS GAME_DATE " +
             "FROM individual_games WHERE SPORT_TYPE = ?")) {
        
        ps.setString(1, sportType);
        ResultSet rs = ps.executeQuery();
        
        boolean gamesFound = false;
        while (rs.next()) {
            // Retrieve game details
            String gameName = rs.getString("GAME_NAME");
            String venue = rs.getString("VENUE");
            String gameDate = rs.getString("GAME_DATE"); // formatted as 'YYYY-MM-DD'
            
            // Format game details and add to combo box
            String gameDetails = gameName + " | " + venue + " | " + gameDate;
            sports_combo.addItem(gameDetails);
            
            gamesFound = true;
        }
        
        if (!gamesFound) {
            System.out.println("No games found for sport type: " + sportType);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}


    private void con_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_btnActionPerformed
    String selectedGame = (String) sports_combo.getSelectedItem();
    String username = UserSession.getInstance().getUsername();

    // Retrieve the GAME_ID for the selected game
    String gameId = "";
    
    if (selectedGame != null && !selectedGame.isEmpty()) {
        // Extract game details from the selected game (assuming combo box item is in the format: "GameName | Venue | Date")
        String[] gameDetails = selectedGame.split(" \\| ");
        String gameName = gameDetails[0];
        String venue = gameDetails[1];
        String gameDate = gameDetails[2];

        System.out.println("Selected game name: " + gameName); 
        System.out.println("Selected venue: " + venue); 
        System.out.println("Selected date: " + gameDate); 

        // Fetch the GAME_ID based on the game name, venue, and date
        try (Connection conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
             PreparedStatement ps = conn.prepareStatement("SELECT GAME_ID, NO_OF_PARTICIPANTS, MAX_PARTICIPANTS FROM individual_games WHERE GAME_NAME = ? AND VENUE = ? AND GAME_DATE = TO_DATE(?, 'YYYY-MM-DD')")) {
            ps.setString(1, gameName);
            ps.setString(2, venue);
            ps.setString(3, gameDate);
            ResultSet rs = ps.executeQuery();

            int totalCapacity = 0;  // Total number of participants allowed
            int currentParticipants = 0;  // Current registered participants

            if (rs.next()) {
                gameId = rs.getString("GAME_ID");
                totalCapacity = rs.getInt("NO_OF_PARTICIPANTS");  // Get total capacity (entered by admin)
                currentParticipants = rs.getInt("MAX_PARTICIPANTS");  // Get current registered participants
                System.out.println("Retrieved GAME_ID: " + gameId);
                System.out.println("Current participants: " + currentParticipants + " / Total capacity: " + totalCapacity);
            } else {
                System.out.println("No GAME_ID found for game: " + gameName); 
            }
            
            // Ensure there is still space for a new participant
            if (currentParticipants < totalCapacity) {
                // Proceed only if a valid GAME_ID was found
                if (gameId != null && !gameId.isEmpty()) {
                    // Check if the player is already registered for the selected game
                    boolean isAlreadyRegistered = false;
                    try (PreparedStatement psCheck = conn.prepareStatement("SELECT * FROM game_participants WHERE GAME_ID = ? AND USERNAME = ?")) {
                        psCheck.setString(1, gameId);
                        psCheck.setString(2, username);
                        ResultSet rsCheck = psCheck.executeQuery();

                        if (rsCheck.next()) {
                            isAlreadyRegistered = true;
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }

                    if (isAlreadyRegistered) {
                        JOptionPane.showMessageDialog(this, "You are already registered for this game!");
                    } else {
                        // Register the player for the game and update the participant count
                        try (PreparedStatement psInsert = conn.prepareStatement("INSERT INTO game_participants (GAME_ID, USERNAME) VALUES (?, ?)")) {
                            psInsert.setString(1, gameId);  
                            psInsert.setString(2, username);  
                            psInsert.executeUpdate();
                            System.out.println("Successfully inserted participant with GAME_ID: " + gameId);

                            // Update current registered participant count (MAX_PARTICIPANTS)
                            try (PreparedStatement updatePs = conn.prepareStatement("UPDATE individual_games SET MAX_PARTICIPANTS = MAX_PARTICIPANTS + 1 WHERE GAME_ID = ?")) {
                                updatePs.setString(1, gameId);
                                updatePs.executeUpdate();
                                System.out.println("Participant count updated for GAME_ID: " + gameId);
                            }

                            JOptionPane.showMessageDialog(this, "Successfully registered for the game!");
                            
                            // Navigate to the main page
                            new Main_Page_1().setVisible(true);
                            this.dispose();
                        } catch (SQLException e) {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog(this, "Error registering for the game: " + e.getMessage());
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Could not register for the game. No valid GAME_ID found.");
                }
            } else {
                // If the participant count has reached the total capacity, show an error message
                JOptionPane.showMessageDialog(this, "Registration closed. Maximum number of participants reached.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    } else {
        System.out.println("No game selected from combo box!");
        JOptionPane.showMessageDialog(this, "Please select a game to register.");
    }
    }//GEN-LAST:event_con_btnActionPerformed

    private void con_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_btn1ActionPerformed
        // TODO add your handling code here:
       new Main_Page_1().setVisible(true);  
       this.dispose();
    }//GEN-LAST:event_con_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Indiv_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Indiv_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Indiv_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Indiv_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Indiv_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton con_btn;
    private javax.swing.JButton con_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> sports_combo;
    // End of variables declaration//GEN-END:variables
}
